import { Card } from "../interfaces/Card";

const allCards: Card[] = [
  { value: 2, color: "s", id: "2s" },
  { value: 3, color: "s", id: "3s" },
  { value: 4, color: "s", id: "4s" },
  { value: 5, color: "s", id: "5s" },
  { value: 6, color: "s", id: "6s" },
  { value: 7, color: "s", id: "7s" },
  { value: 8, color: "s", id: "8s" },
  { value: 9, color: "s", id: "9s" },
  { value: 10, color: "s", id: "10s" },
  { value: 11, color: "s", id: "11s" },
  { value: 12, color: "s", id: "12s" },
  { value: 13, color: "s", id: "13s" },
  { value: 14, color: "s", id: "14s" },
  { value: 2, color: "h", id: "2h" },
  { value: 3, color: "h", id: "3h" },
  { value: 4, color: "h", id: "4h" },
  { value: 5, color: "h", id: "5h" },
  { value: 6, color: "h", id: "6h" },
  { value: 7, color: "h", id: "7h" },
  { value: 8, color: "h", id: "8h" },
  { value: 9, color: "h", id: "9h" },
  { value: 10, color: "h", id: "10h" },
  { value: 11, color: "h", id: "11h" },
  { value: 12, color: "h", id: "12h" },
  { value: 13, color: "h", id: "13h" },
  { value: 14, color: "h", id: "14h" },
  { value: 2, color: "d", id: "2d" },
  { value: 3, color: "d", id: "3d" },
  { value: 4, color: "d", id: "4d" },
  { value: 5, color: "d", id: "5d" },
  { value: 6, color: "d", id: "6d" },
  { value: 7, color: "d", id: "7d" },
  { value: 8, color: "d", id: "8d" },
  { value: 9, color: "d", id: "9d" },
  { value: 10, color: "d", id: "10d" },
  { value: 11, color: "d", id: "11d" },
  { value: 12, color: "d", id: "12d" },
  { value: 13, color: "d", id: "13d" },
  { value: 14, color: "d", id: "14d" },
  { value: 2, color: "c", id: "2c" },
  { value: 3, color: "c", id: "3c" },
  { value: 4, color: "c", id: "4c" },
  { value: 5, color: "c", id: "5c" },
  { value: 6, color: "c", id: "6c" },
  { value: 7, color: "c", id: "7c" },
  { value: 8, color: "c", id: "8c" },
  { value: 9, color: "c", id: "9c" },
  { value: 10, color: "c", id: "10c" },
  { value: 11, color: "c", id: "11c" },
  { value: 12, color: "c", id: "12c" },
  { value: 13, color: "c", id: "13c" },
  { value: 14, color: "c", id: "14c" },
];

export default allCards;
